In [ ]:
#https://blog.naver.com/choi_s_h 
# 3차원 배열 설명

In [ ]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
data_path = '/content/drive/MyDrive/Dacon/비트코인 예측/data'
train_x_df = pd.read_csv(data_path + '/train_x_df.csv')
train_y_df = pd.read_csv(data_path + '/train_y_df.csv')
test_x_df = pd.read_csv(data_path + '/test_x_df.csv')

In [ ]:
train_x_df.shape

#괄호 친게 메쏘드, 괄호 안친것은 변수, 속성값! 

#여기서 train_x_df는 하나의 객체이고 그 안에 변수 중에 하나가 shape이다

#train_x_df 객체의 형태? 사이즈? 크기 같은느낌

(10159560, 12)

In [ ]:
train_x_df.tail()

sample_id  time  coin_index  ...    trades  tb_base_av  tb_quote_av
10159555       7361  1375           8  ...  2.245034    6.229020  1494.727417
10159556       7361  1376           8  ...  2.211651    3.056139   733.490601
10159557       7361  1377           8  ...  1.260224    2.284546   548.042297
10159558       7361  1378           8  ...  0.826239    0.516497   123.819839
10159559       7361  1379           8  ...  0.642631    0.732091   175.527679

[5 rows x 12 columns]

In [ ]:
# train x와 train y의 행의 갯수가 다르다 
# 왜냐하면 원래 3차원의 데이터인데 2차원으로 표현해놓다 보니 행 수가 다르다 ( 코인의 index값을 구분해야 함 2차원으로 쓰려면)


In [ ]:
train_x_df.shape

(10159560, 12)

In [ ]:
train_y_df.shape

(883440, 12)

In [ ]:
test_x_df.shape

(730020, 12)

In [ ]:
train_x_df.head(10)

sample_id  time  coin_index  ...      trades    tb_base_av    tb_quote_av
0          0     0           7  ...  451.157288  7.326834e+05   37725.183594
1          0     1           7  ...   39.231071  0.000000e+00       0.000000
2          0     2           7  ...   58.846603  1.664967e+04     857.377808
3          0     3           7  ...  431.541779  2.189147e+06  112811.046875
4          0     4           7  ...  176.539810  0.000000e+00       0.000000
5          0     5           7  ...  255.001953  1.226671e+06   63211.722656
6          0     6           7  ...   78.462143  1.567674e+05    8085.568359
7          0     7           7  ...    0.000000  0.000000e+00       0.000000
8          0     8           7  ...   39.231071  3.663005e+04    1890.110596
9          0     9           7  ...  294.233032  4.946646e+05   25505.400391

[10 rows x 12 columns]

In [ ]:
train_x_df.tail()

sample_id  time  coin_index  ...    trades  tb_base_av  tb_quote_av
10159555       7361  1375           8  ...  2.245034    6.229020  1494.727417
10159556       7361  1376           8  ...  2.211651    3.056139   733.490601
10159557       7361  1377           8  ...  1.260224    2.284546   548.042297
10159558       7361  1378           8  ...  0.826239    0.516497   123.819839
10159559       7361  1379           8  ...  0.642631    0.732091   175.527679

[5 rows x 12 columns]

In [ ]:
train_x_df.info()  #df에 대한 Dtype등을 알 수 있음. 타입 알기 위한것

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10159560 entries, 0 to 10159559
Data columns (total 12 columns):
 #   Column       Dtype  
---  ------       -----  
 0   sample_id    int64  
 1   time         int64  
 2   coin_index   int64  
 3   open         float64
 4   high         float64
 5   low          float64
 6   close        float64
 7   volume       float64
 8   quote_av     float64
 9   trades       float64
 10  tb_base_av   float64
 11  tb_quote_av  float64
dtypes: float64(9), int64(3)
memory usage: 930.1 MB


In [ ]:
train_x_df.describe()  #기술 통계값 알기 위한것. 평균, 표편, 최소, 최대 등등
# 대충 4분위수로 어떻게 분포되어있는지 알 수 있음.



sample_id          time  ...    tb_base_av   tb_quote_av
count  1.015956e+07  1.015956e+07  ...  1.015956e+07  1.015956e+07
mean   3.680500e+03  6.895000e+02  ...  3.647911e+05  2.106137e+04
std    2.125226e+03  3.983716e+02  ...  5.268894e+06  1.117901e+05
min    0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
25%    1.840000e+03  3.447500e+02  ...  5.671815e-03  1.066213e+01
50%    3.680500e+03  6.895000e+02  ...  1.039115e+00  1.152704e+02
75%    5.521000e+03  1.034250e+03  ...  9.016594e+03  4.863686e+03
max    7.361000e+03  1.379000e+03  ...  7.340513e+09  2.320023e+07

[8 rows x 12 columns]

In [1]:
import pandas as pd
import numpy as np

In [36]:
data_path = '/content/drive/MyDrive/Dacon/비트코인 예측/data'
train_x_df = pd.read_csv(data_path + '/train_x_df.csv')
train_y_df = pd.read_csv(data_path + '/train_y_df.csv')
test_x_df = pd.read_csv(data_path + '/test_x_df.csv')

In [18]:
#train_x_df.loc[:,:]
#train_x_df.loc["time"]
train_x_df.columns.to_list()

['sample_id',
 'time',
 'coin_index',
 'open',
 'high',
 'low',
 'close',
 'volume',
 'quote_av',
 'trades',
 'tb_base_av',
 'tb_quote_av']

In [28]:
list1=[1,2,3,4,5]
array_1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
array_1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [30]:
df=pd.DataFrame(array_1, columns=['a','b','c','d','e'], index=['y','b'])
df

a  b  c  d  e
y  1  2  3  4  5
b  1  2  3  4  5

In [31]:
df_array=df.values
df_array

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [32]:
np.transpose(df_array)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [38]:
train_x_df.set_index("open")


sample_id  time  coin_index  ...      trades    tb_base_av    tb_quote_av
open                                   ...                                         
1.010004          0     0           7  ...  451.157288  7.326834e+05   37725.183594
1.009808          0     1           7  ...   39.231071  0.000000e+00       0.000000
1.009808          0     2           7  ...   58.846603  1.664967e+04     857.377808
1.010200          0     3           7  ...  431.541779  2.189147e+06  112811.046875
1.010985          0     4           7  ...  176.539810  0.000000e+00       0.000000
...             ...   ...         ...  ...         ...           ...            ...
1.000668       7361  1375           8  ...    2.245034  6.229020e+00    1494.727417
1.001627       7361  1376           8  ...    2.211651  3.056139e+00     733.490601
1.001294       7361  1377           8  ...    1.260224  2.284546e+00     548.042297
1.000709       7361  1378           8  ...    0.826239  5.164965e-01     123.819839
1.000000       7361  1379           8  ...    0.642631  7.320906e-01     175.527679

[10159560 rows x 11 columns]